site: Study Guide &amp; Notes
baseurl: ""
url: study.joshuafayer.com
permalink: /:categories/:title/
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
plugins:
  - jekyll-sitemap
